require 'codebreaker_captainjns'
require 'i18n'
require_relative './entities/config/i18n'
require 'rack'
require_relative 'entities/table_row'
require_relative 'entities/data_utils'
require_relative 'entities/cb_game'
